name: cbj_hub
description: Easy to use open source Hub to control your smart devices from one app.
version: 1.0.1
homepage: https://cybearjinni.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Contains utility classes in the style of dart:async to work with asynchronous computations.
  async: ^2.8.2
  # Collection of cyclic redundancy check (CRC) routines as Dart converters.
  crclib:
    git:
      url: https://github.com/google/crclib.dart.git
      ref: nullsafety
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.0
  # Allow returning more than one type of object
  equatable: ^2.0.3
  # Annotations for freezed
  freezed_annotation: ^0.14.3
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.2.0
  # High performance, open-source universal RPC framework
  grpc: ^3.0.1
  # Convenient code generator for get_it
  injectable: ^1.4.1
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.1.0
  # Dart Build System builders for handling JSON.
  json_serializable: ^4.1.3
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^0.9.1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.5.3
  # A server and browser based MQTT client for Dart.
  mqtt_client: ^9.5.0
  # Service discovery over multicast DNS (mDNS), Bonjour, and Avahi.
  multicast_dns: ^0.3.0
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^2.0.0
  # Extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.1
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.4
  # Dart library for controlling Yeelight products over LAN.
  yeedart: ^0.3.0

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # A generator for injectable library
  # Code generator for unions/pattern-matching/copy.
  freezed: ^0.14.2
  # Injectable is a convenient code generator for get_it.
  injectable_generator: ^1.4.1
  # Library for mocks
  mockito: ^5.0.14
  # The Dart analyzer settings and best practices used internally at Google.
  pedantic: ^1.11.1
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.17.10
